# Tell snakemake to use Slurm
executor: slurm

# Maximum number of parallel jobs
jobs: 10  

# Default resources for all rules (overwritten by set-threads and set-resources)
default-resources:
  slurm_partition: batch
    
# Set number of threads for rule(s) ("threads" is equal to Slurm's "cpus-per-task")
set-threads:
  extract_submatrix: 1

# Set other resources (memory, runtime, GPU) for specific rule(s)
# Value formats are described in: 
# https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#standard-resources
set-resources:
  extract_submatrix:
    mem: 500MB
    runtime: 1h
    # To request a GPU, you can use the following two lines
    # partition: gpu
    # slurm_extra: "'--gres=gpu:1'"
